/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * blocky API
 * REST API for Blocky, a DNS proxy and ad-blocker for the local network.

For features, configuration, and installation see the [project documentation](https://0xerr0r.github.io/blocky/) and the [README](https://github.com/0xERR0R/blocky/blob/main/README.md).
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ApiQueryRequest,
  ApiQueryResult
} from '../../schemas';





/**
 * Performs DNS query
 * @summary Performs DNS query
 */
export const dnsQuery = (
    apiQueryRequest: ApiQueryRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiQueryResult>> => {


    return axios.post(
      `/api/query`,
      apiQueryRequest,options
    );
  }



export const getDnsQueryMutationOptions = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dnsQuery>>, TError,{data: ApiQueryRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof dnsQuery>>, TError,{data: ApiQueryRequest}, TContext> => {

const mutationKey = ['dnsQuery'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dnsQuery>>, {data: ApiQueryRequest}> = (props) => {
          const {data} = props ?? {};

          return  dnsQuery(data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DnsQueryMutationResult = NonNullable<Awaited<ReturnType<typeof dnsQuery>>>
    export type DnsQueryMutationBody = ApiQueryRequest
    export type DnsQueryMutationError = AxiosError<string>

    /**
 * @summary Performs DNS query
 */
export const useDnsQuery = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dnsQuery>>, TError,{data: ApiQueryRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof dnsQuery>>,
        TError,
        {data: ApiQueryRequest},
        TContext
      > => {
      return useMutation(getDnsQueryMutationOptions(options), queryClient);
    }
