/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * blocky API
 * REST API for Blocky, a DNS proxy and ad-blocker for the local network.

For features, configuration, and installation see the [project documentation](https://0xerr0r.github.io/blocky/) and the [README](https://github.com/0xERR0R/blocky/blob/main/README.md).
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';





/**
 * Removes all DNS responses from cache
 * @summary Clears the DNS response cache
 */
export const cacheFlush = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.post(
      `/api/cache/flush`,undefined,options
    );
  }



export const getCacheFlushMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cacheFlush>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof cacheFlush>>, TError,void, TContext> => {

const mutationKey = ['cacheFlush'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cacheFlush>>, void> = () => {


          return  cacheFlush(axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CacheFlushMutationResult = NonNullable<Awaited<ReturnType<typeof cacheFlush>>>

    export type CacheFlushMutationError = AxiosError<unknown>

    /**
 * @summary Clears the DNS response cache
 */
export const useCacheFlush = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cacheFlush>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cacheFlush>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getCacheFlushMutationOptions(options), queryClient);
    }
