/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * blocky API
 * REST API for Blocky, a DNS proxy and ad-blocker for the local network.

For features, configuration, and installation see the [project documentation](https://0xerr0r.github.io/blocky/) and the [README](https://github.com/0xERR0R/blocky/blob/main/README.md).
 * OpenAPI spec version: 1.0
 */
import type { ApiListCountsAllowlist } from './apiListCountsAllowlist';
import type { ApiListCountsDenylist } from './apiListCountsDenylist';

/**
 * Current per-group list entry counts (point-in-time, not windowed).
 */
export interface ApiListCounts {
  denylist: ApiListCountsDenylist;
  allowlist: ApiListCountsAllowlist;
}
