/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * blocky API
 * REST API for Blocky, a DNS proxy and ad-blocker for the local network.

For features, configuration, and installation see the [project documentation](https://0xerr0r.github.io/blocky/) and the [README](https://github.com/0xERR0R/blocky/blob/main/README.md).
 * OpenAPI spec version: 1.0
 */
import type { ApiCacheStats } from './apiCacheStats';
import type { ApiHourPoint } from './apiHourPoint';
import type { ApiListCounts } from './apiListCounts';
import type { ApiNameCount } from './apiNameCount';
import type { ApiStatsByQueryType } from './apiStatsByQueryType';
import type { ApiStatsByResponseCode } from './apiStatsByResponseCode';
import type { ApiStatsByResponseType } from './apiStatsByResponseType';
import type { ApiStatsSummary } from './apiStatsSummary';

/**
 * In-memory DNS statistics snapshot.
 */
export interface ApiStats {
  /** Start of the covered window for the windowed fields (not the gauges). UTC (RFC 3339). */
  start: string;
  /** Snapshot time. UTC (RFC 3339). */
  end: string;
  summary: ApiStatsSummary;
  /** Raw per-RType counts over the window (CACHED, BLOCKED, ...). */
  byResponseType: ApiStatsByResponseType;
  /** Counts per DNS query type over the window (A, AAAA, ...). */
  byQueryType: ApiStatsByQueryType;
  /** Counts per DNS response code over the window (NOERROR, NXDOMAIN, ...). */
  byResponseCode: ApiStatsByResponseCode;
  /** Per-hour time series over the window. */
  perHour: ApiHourPoint[];
  topDomains: ApiNameCount[];
  topBlockedDomains: ApiNameCount[];
  topClients: ApiNameCount[];
  lists: ApiListCounts;
  cache: ApiCacheStats;
}
