/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * blocky API
 * REST API for Blocky, a DNS proxy and ad-blocker for the local network.

For features, configuration, and installation see the [project documentation](https://0xerr0r.github.io/blocky/) and the [README](https://github.com/0xERR0R/blocky/blob/main/README.md).
 * OpenAPI spec version: 1.0
 */

/**
 * Curated outcome categories over the window (server computes the mapping).
 */
export interface ApiStatsSummary {
  /** Total queries received in the window. */
  queries: number;
  cached: number;
  forwarded: number;
  blocked: number;
  local: number;
  dropped: number;
  errors: number;
  avgResponseMs: number;
  cacheHitRate: number;
}
