/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * blocky API
 * REST API for Blocky, a DNS proxy and ad-blocker for the local network.

For features, configuration, and installation see the [project documentation](https://0xerr0r.github.io/blocky/) and the [README](https://github.com/0xERR0R/blocky/blob/main/README.md).
 * OpenAPI spec version: 1.0
 */

export type DisableBlockingParams = {
/**
 * duration of blocking (Example: 300s, 5m, 1h, 5m30s)
 */
duration?: string;
/**
 * groups to disable (comma separated). If empty, disable all groups
 */
groups?: string;
};
