/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * blocky API
 * REST API for Blocky, a DNS proxy and ad-blocker for the local network.

For features, configuration, and installation see the [project documentation](https://0xerr0r.github.io/blocky/) and the [README](https://github.com/0xERR0R/blocky/blob/main/README.md).
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ApiBlockingStatus,
  DisableBlockingParams
} from '../../schemas';





/**
 * disable the blocking status
 * @summary Disable blocking
 */
export const disableBlocking = (
    params?: DisableBlockingParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.get(
      `/api/blocking/disable`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getDisableBlockingQueryKey = (params?: DisableBlockingParams,) => {
    return [
    `/api/blocking/disable`, ...(params ? [params] : [])
    ] as const;
    }


export const getDisableBlockingQueryOptions = <TData = Awaited<ReturnType<typeof disableBlocking>>, TError = AxiosError<string>>(params?: DisableBlockingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof disableBlocking>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDisableBlockingQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof disableBlocking>>> = ({ signal }) => disableBlocking(params, { signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof disableBlocking>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DisableBlockingQueryResult = NonNullable<Awaited<ReturnType<typeof disableBlocking>>>
export type DisableBlockingQueryError = AxiosError<string>


export function useDisableBlocking<TData = Awaited<ReturnType<typeof disableBlocking>>, TError = AxiosError<string>>(
 params: undefined |  DisableBlockingParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof disableBlocking>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof disableBlocking>>,
          TError,
          Awaited<ReturnType<typeof disableBlocking>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDisableBlocking<TData = Awaited<ReturnType<typeof disableBlocking>>, TError = AxiosError<string>>(
 params?: DisableBlockingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof disableBlocking>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof disableBlocking>>,
          TError,
          Awaited<ReturnType<typeof disableBlocking>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDisableBlocking<TData = Awaited<ReturnType<typeof disableBlocking>>, TError = AxiosError<string>>(
 params?: DisableBlockingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof disableBlocking>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Disable blocking
 */

export function useDisableBlocking<TData = Awaited<ReturnType<typeof disableBlocking>>, TError = AxiosError<string>>(
 params?: DisableBlockingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof disableBlocking>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDisableBlockingQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * enable the blocking status
 * @summary Enable blocking
 */
export const enableBlocking = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.get(
      `/api/blocking/enable`,options
    );
  }




export const getEnableBlockingQueryKey = () => {
    return [
    `/api/blocking/enable`
    ] as const;
    }


export const getEnableBlockingQueryOptions = <TData = Awaited<ReturnType<typeof enableBlocking>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enableBlocking>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEnableBlockingQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof enableBlocking>>> = ({ signal }) => enableBlocking({ signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof enableBlocking>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EnableBlockingQueryResult = NonNullable<Awaited<ReturnType<typeof enableBlocking>>>
export type EnableBlockingQueryError = AxiosError<unknown>


export function useEnableBlocking<TData = Awaited<ReturnType<typeof enableBlocking>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof enableBlocking>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof enableBlocking>>,
          TError,
          Awaited<ReturnType<typeof enableBlocking>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEnableBlocking<TData = Awaited<ReturnType<typeof enableBlocking>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enableBlocking>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof enableBlocking>>,
          TError,
          Awaited<ReturnType<typeof enableBlocking>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEnableBlocking<TData = Awaited<ReturnType<typeof enableBlocking>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enableBlocking>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Enable blocking
 */

export function useEnableBlocking<TData = Awaited<ReturnType<typeof enableBlocking>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enableBlocking>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEnableBlockingQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * get current blocking status
 * @summary Blocking status
 */
export const blockingStatus = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiBlockingStatus>> => {


    return axios.get(
      `/api/blocking/status`,options
    );
  }




export const getBlockingStatusQueryKey = () => {
    return [
    `/api/blocking/status`
    ] as const;
    }


export const getBlockingStatusQueryOptions = <TData = Awaited<ReturnType<typeof blockingStatus>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blockingStatus>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBlockingStatusQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof blockingStatus>>> = ({ signal }) => blockingStatus({ signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof blockingStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BlockingStatusQueryResult = NonNullable<Awaited<ReturnType<typeof blockingStatus>>>
export type BlockingStatusQueryError = AxiosError<unknown>


export function useBlockingStatus<TData = Awaited<ReturnType<typeof blockingStatus>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof blockingStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof blockingStatus>>,
          TError,
          Awaited<ReturnType<typeof blockingStatus>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBlockingStatus<TData = Awaited<ReturnType<typeof blockingStatus>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blockingStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof blockingStatus>>,
          TError,
          Awaited<ReturnType<typeof blockingStatus>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBlockingStatus<TData = Awaited<ReturnType<typeof blockingStatus>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blockingStatus>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Blocking status
 */

export function useBlockingStatus<TData = Awaited<ReturnType<typeof blockingStatus>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blockingStatus>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBlockingStatusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






